/**
 *  机构客户业务字段与名称对应配置
 *  @author linbk
 */
export default {
    // 涉税信息
    TAX_INFO: {
        TAX_RESIDENT_TYPE: "1",
        PASSIVE_NFE: "1",
        GET_INVEST_CERFLAG: "",
        NAME_ENG: "",
        ADDRESS_TYPE: "",
        ADDRESS: "",
        ADDRESS_ENG: "",
        CITY_ENG: "",
        PROVINCE_ENG: "",
        NATION_ENG: "",
        BIRTH_ADDRESS: "",
        CITIZENSHIP: "",
        CITIZENSHIP2: "",
        CITIZENSHIP3: "",
        CTRL_NO: "",
        CTRL_NON_RESIDENT: "",
        DIFF_INFO: [],
        HAS_TAXPAYER_IDNO: "",
        HAS_TAXPAYER_IDNO2: "",
        HAS_TAXPAYER_IDNO3: "",
        LIVING_COUNTRY: "",
        NO_CHK_ORG: "",
        NO_TAXPAYERID_REASON: "",
        NO_TAXPAYERID_REASON2: "",
        NO_TAXPAYERID_REASON3: "",
        OPER_TYPE: "1",
        OPP_NO_TAXPAYERID_REASON: "",
        OPP_NO_TAXPAYERID_REASON2: "",
        OPP_NO_TAXPAYERID_REASON3: "",
        TAXPAYER_IDNO: "",
        TAXPAYER_IDNO2: "",
        TAXPAYER_IDNO3: "",
    },
    // 控制人涉税信息 
    CONTROLLER_TAX_INFO: {
        CTRL_NO: "",
        TAX_RESIDENT_TYPE: "1",
        CTRL_NON_RESIDENT: "",
        CTRL_TYPE: "",
        CUST_NAME: "",
        CTRL_SHARE_RATIO: "",
        NAME_ENG: "",
        SURNAME_ENG: "",
        ADDRESS_ENG: "",
        CITY_ENG: "",
        PROVINCE_ENG: "",
        NATION_ENG: "",
        ADDRESS: "",
        BIRTH_ADDRESS_ENG: "",
        BIRTH_CITY_ENG: "",
        BIRTH_PROVINCE_ENG: "",
        BIRTH_NATION_ENG: "",
        BIRTH_ADDRESS: "",
        BIRTHDAY: "",
        BIRTH_COUNTRY: "",
        CITIZENSHIP: "",
        CITIZENSHIP2: "",
        CITIZENSHIP3: "",
        DIFF_INFO: [],
        HAS_TAXPAYER_IDNO: "",
        HAS_TAXPAYER_IDNO2: "",
        HAS_TAXPAYER_IDNO3: "",
        LIVING_COUNTRY: "",
        NO_TAXPAYERID_REASON: "",
        NO_TAXPAYERID_REASON2: "",
        NO_TAXPAYERID_REASON3: "",
        OPER_TYPE: "3", // 默认不变
        OPP_NO_TAXPAYERID_REASON: "",
        OPP_NO_TAXPAYERID_REASON2: "",
        OPP_NO_TAXPAYERID_REASON3: "",
        TAXPAYER_IDNO: "",
        TAXPAYER_IDNO2: "",
        TAXPAYER_IDNO3: "",
        titleText: "",
    },
};
